[theme]
font_color = #353100
font_path = /usr/share/fonts/TTF/JetBrainsMonoNerdFont-Regular.ttf
font_size = 14.0
background_color = #15140c
window_rounding = 10.0
frame_rounding = 10.0
background_blur = 0.55
hover_color = #d1c973
active_color = cdc8a3
wallpaper_width_ratio = 0.9
