[bar]
scale = 0.8500000238418579
button-variant = "basic"

[[bar.layout]]
monitor = "*"
show = true
left = [
    "media",
    "cpu",
    "dashboard",
    "hyprsunset",
    "ram",
    "hyprland-workspaces",
]
center = ["clock"]
right = [
    "bluetooth",
    "network",
    "microphone",
    "volume",
]

[styling]
theme-provider = "matugen"
