# Background / foreground
background #15140c
foreground #e7e2d5

# Cursor
cursor #d1c973
cursor_text_color #353100

# Selection
selection_background #4a482c
selection_foreground #e9e4be

# Tabs
active_tab_background #d1c973
active_tab_foreground #353100

inactive_tab_background #212017
inactive_tab_foreground #cbc7b5

# Borders
active_border_color #d1c973
inactive_border_color #949181
