# ─────────────────────
# Font
# ─────────────────────

font_size 12.0


# ─────────────────────
# Window
# ─────────────────────

window_padding_width 8

# ─────────────────────
# Scrollback
# ─────────────────────
scrollback_lines 10000
scrollback_pager_history_size 20


# ─────────────────────
# Cursor
# ─────────────────────
cursor_trail 3

# ─────────────────────
# Tabs
# ─────────────────────

tab_bar_edge top
tab_bar_style powerline
tab_bar_min_tabs 2


# ─────────────────────
# Layout
# ─────────────────────
enabled_layouts splits

# ─────────────────────
# Clipboard
# ─────────────────────
copy_on_select clipboard

include matugen.conf
