# Basic
background #0e1514
foreground #dde4e2

# Cursor
cursor #81d5cc
cursor_text_color #003733

# Selection
selection_background #324b48
selection_foreground #cce8e4

# URLs
url_color #afc9e7

# ANSI
color0  #0e1514
color1  #ffb4ab
color2  #afc9e7
color3  #b1ccc8
color4  #81d5cc
color5  #afc9e7
color6  #b1ccc8
color7  #dde4e2

color8  #3f4947
color9  #93000a
color10 #2f4961
color11 #324b48
color12 #00504b
color13 #324b48
color14 #2f4961
color15 #bec9c6

# Tabs
active_tab_background #81d5cc
active_tab_foreground #003733

inactive_tab_background #1a2120
inactive_tab_foreground #bec9c6

# Borders
active_border_color #81d5cc
inactive_border_color #899391
