# Background / foreground
background #14140c
foreground #e6e2d5

# Cursor
cursor #ceca75
cursor_text_color #333200

# Selection
selection_background #49482c
selection_foreground #e8e4bf

# Tabs
active_tab_background #ceca75
active_tab_foreground #333200

inactive_tab_background #212018
inactive_tab_foreground #cac7b6

# Borders
active_border_color #ceca75
inactive_border_color #949181
