[theme]
font_color = #003733
font_path = /usr/share/fonts/TTF/JetBrainsMonoNerdFont-Regular.ttf
font_size = 14.0
background_color = #0e1514
window_rounding = 10.0
frame_rounding = 10.0
background_blur = 0.55
hover_color = #81d5cc
active_color = b1ccc8
wallpaper_width_ratio = 0.9
