[styling]
theme-provider = "wayle"

[styling.palette]
bg = "#15140c"
surface = "#1d1c14"
elevated = "#212017"

fg = "#e7e2d5"
fg-muted = "#cbc7b5"

primary = "#d1c973"

red = "#ffb4ab"
yellow = "#a6d0b9"
green = "#cdc8a3"
blue = "#d1c973"
