[bar]
scale = 0.800000011920929
padding = 0.0
module-gap = 1.0
location = "left"
bg = "transparent"
background-opacity = 83
button-variant = "icon-square"
button-label-size = 0.949999988079071
button-rounding = "lg"
button-group-rounding = "lg"
dropdown-opacity = 94

[[bar.layout]]
monitor = "*"
show = true
left = [
    "dashboard",
    { name = "cpuandram", modules = [
    "cpu",
    "ram",
] },
]
center = [
    "media",
    "hyprland-workspaces",
]
right = [
    "bluetooth",
    { name = "group", modules = ["volume"] },
    "notifications",
    "clock",
    "systray",
]

[modules.bluetooth]
label-show = false

[modules.clock]
format = "%I:%M"

[modules.hyprland-workspaces]
min-workspace-count = 5
app-icons-show = true

[modules.media]
format = "{{ title }}"
label-show = false

[modules.volume]
label-show = false

[wallpaper]
transition-type = "fade"
cycling-enabled = true
cycling-directory = "/home/cocoa6874/Downloads/wallpapers/images.jpg"
cycling-interval-mins = 1
